### ISSUE TITLE
false output for C++ inference

### ISSUE THREAD

**Issue by mht1421** [ajuric/aliked-tensorrt#1]
Thanks for the export code to onnx, I tried to use it in C++, for the preprocess I just normalized the input to 0-1 and transformed to float32. But I couldn't get an appropriate output using the onnx models. Is there something I am doing wrong?

**Comment by ajuric** [comment]
That could be due to a lot of stuff.
Here is the execution of onnx model in Python: https://github.com/ajuric/aliked-tensorrt/blob/main/convert_pytorch_to_onnx.py#L163

During the conversion to ONNX, I get same outputs as in Pytorch, so check your steps again.

Don't forget to do the same [preprocessing](https://github.com/ajuric/aliked-tensorrt/blob/main/convert_pytorch_to_onnx.py#L163) and [post-processing](https://github.com/ajuric/aliked-tensorrt/blob/main/nets/aliked.py#L222) (e.g. scaling keypoints back to [0-Height, 0-Width]) as in ALIKED model.

**Comment by mht1421** [comment]
Thank you for the fast reply, I got a good output. Just another question please, have you tested lightglue with the aliked features also?

**Comment by ajuric** [comment]
Using LightGlue and ALIKED together has been done here: https://github.com/cvg/glue-factory?tab=readme-ov-file#available-models (see the second table in the linked section).

It's also mentioned/tested [here](https://x.com/ducha_aiki/status/1750461472134631829?s=20) and [here](https://x.com/ducha_aiki/status/1749740461596565639?s=20) .
